services:
  CED_APP:
    image: prawee/strapi:latest
    container_name: CED_CYBER_APP
    ports:
    - ${APP_PORT}:1337
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: CED_CYBER_DB
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASS}"
